{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-b
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-b
  template:
    metadata:
      labels:
        app: ms-b
    spec:
      containers:
      - name: ms-b
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.global.kafka.brokerName }}:{{ .Values.global.kafka.internalPort }}"
        - name: REDIS_HOST
          value: {{ .Values.redisHost | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redisPort | quote }}

        readinessProbe:
          tcpSocket:
            port: {{ .Values.port }}

        livenessProbe:
          tcpSocket:
            port: {{ .Values.port }}
{{- end }}
